### ISSUE TITLE
How do I change the local port?

### ISSUE THREAD

**Issue by stereokai** [ryanj/config-multipaas#4]
@ryanj How do I change the local port? Documentation couldn't be any less clear :)

I looked in the other two linked projects, and tried following the examples there, with the below code:

``` js
var port    = config.get('PORT', 7666),
    address = config.get('IP', 'localhost');

server = app.listen(
  port,
  address,
  function () {
    console.log('Application worker ' + process.pid + ' started...');
    console.log( "Listening on " + address + ", port " + port )
});
```

However, the server's still listening on port 8080.

Thanks in advance.

**Comment by ryanj** [comment]
Hi @stereokai:  
From your example, I'm not sure how you are initializing your `config` object.
1. Did you try passing your config overrides into the constructor (as shown [README.md#setup](https://github.com/ryanj/config-multipaas#setup))?
2. Did you try passing your default config values into the resulting config object's `add()` function (also in [README.md#setup](https://github.com/ryanj/config-multipaas#setup))?
3. Did you try reading the `config-chain` docs? `config-multipaas` is an instance of `config-chain`, which can help you merge multiple layers of config data...  If you don't need a full-blown configuration management solution (but you still want cloud defaults) see `cloud-env`.

Since `cloud-env` does not attempt to merge multiple layers of configuration (or maintain compatibility with the `config-chain` interface), it provides a `get` accessor function that allows you to supply a different fallback value each time.  You might want to try that module instead.

Hope this helps.

**Comment by stereokai** [comment]
@ryanj Sorry for not responding earlier, was rather preoccupied.

It's a pretty simple server script for a simple PoC. All I needed to do was change the port the server listened when run locally, because the default (8080) is already used on my laptop.

Apparently multipaas knows to use port 80 on Openshift, so what I ended up doing is simply overriding the port if it equals 8080:

``` JS
let config  = require('config-multipaas')();

let port    = config.get('PORT'),
    address = config.get('IP');

if (port == 8080) port = 7666;

server = app.listen(
  port,
  address,
  function () {
    console.log('Application worker ' + process.pid + ' started...');
    console.log( "Listening on " + address + ", port " + port )
});
```

It seems to work, but it feels hackish. What would be the correct way to do that?

Thanks

**Comment by ryanj** [comment]
```
var cc = require('config-multipaas')
var config = cc().add({ PORT: 7666 })
var port = config.get('PORT')
```
